[package]
name = "mappings_finder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
serde_json = "1.0.79"
reqwest = "0.11.9"
tokio = { version = "1", features = ["full"] }
