name: Deploy

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/ISSUE_TEMPLATE/**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install static-sitemap-cli
        run: npm install static-sitemap-cli

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # Webpack production build
      - name: Webpack production build
        run: |
          cd freeport/frontend/dist
          npm install --save --legacy-peer-deps
          npm run build
        env:
          API_BASE_URL: https://starfish-ql-api.sea-ql.org
      - name: Generate tutorials-book sitemap
        run: |
          cd freeport/frontend/dist
          npx sscli --base https://starfish-ql.sea-ql.org/

      # Deploy GitHub Pages
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: freeport/frontend/dist
          single-commit: true
          clean: true
